services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - database
      - redis
    restart: always
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
    ports: 
      - "3000:3000"
    command: ./bin/rails server -b 0.0.0.0

  worker: &worker
    <<: *app
    ports: []
    command: bundle exec sidekiq

  database:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis:7.2

  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      cluster.name: "elasticsearch-rails"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db_data:
  esdata1: